### ISSUE TITLE
Clarify purpose of this repo in the README

### ISSUE THREAD

**Issue by samtuke** [gocept/gtimelog-macosx#45]
Hi, it's unclear to me whether this repo is just documentation on how to install from the main Gtimelog repo, or a fork of that repo, or some additional config files which compliments files found in that repo. Please clarify this in the README file. 

FYI personally I followed your README instructions and used the main Gtimely repo (I did not clone your repo) and Gtimelog is working mostly as expected.

**Comment by icemac** [comment]
In https://github.com/minddistrict/gtimelog-macosx/commit/05c1b37d9f0d06905f1614052ce5122cf0ac7f0c I added a line to the readme telling to clone this repo as it contains a pre-built MacOS app which just needs to be pointed to the correct gtimelog binary.
